In [26]:
from dotenv import load_dotenv
import os
import requests
from pprint import pprint
import pandas as pd
import missingno as mno
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from collections import Counter
import time

load_dotenv()

True

In [2]:
API_KEY = os.getenv("TICKETMASTER_API_KEY")

if not API_KEY:
    raise ValueError("No API key found — check your .env file exists and has TICKETMASTER_API_KEY set")

In [3]:
response = requests.get(
    "https://app.ticketmaster.com/discovery/v2/events.json",
    params={
        "apikey": API_KEY,
        "countryCode": "GB",
        "classificationName": "Music",
        "size": 20,
        "page": 0
    }
)
print(response.status_code)
data = response.json()

200

In [10]:
# Exploring the structure of the data, and what data structures are embedded

data.keys()
data = response.json()

print(type(data))        # <class 'dict'>
print(data.keys())       # dict_keys(['_embedded', '_links', 'page'])

print(type(data['_embedded']))       # <class 'dict'>
print(data['_embedded'].keys())      # dict_keys(['events'])

print(type(data['_embedded']['events']))     # <class 'list'>
print(len(data['_embedded']['events']))      # e.g. 20

print(type(data['_embedded']['events'][0]))  # <class 'dict'>  <- one single event
print(data['_embedded']['events'][0].keys())

<class 'dict'>
dict_keys(['_embedded', '_links', 'page'])
<class 'dict'>
dict_keys(['events'])
<class 'list'>
20
<class 'dict'>
dict_keys(['name', 'type', 'id', 'test', 'url', 'locale', 'images', 'sales', 'dates', 'classifications', 'promoter', 'promoters', 'pleaseNote', 'products', 'accessibility', 'ticketLimit', 'ageRestrictions', 'ticketing', 'nameOrigin', 'ticketTextLines', '_links', '_embedded'])

In [11]:
pprint(data)

{'_embedded': {'events': [{'_embedded': {'attractions': [{'_links': {'self': {'href': '/discovery/v2/attractions/K8vZ9171Qi7?locale=en-us'}},
                                                          'classifications': [{'family': False,
                                                                               'genre': {'id': 'KnvZfZ7vAv1',
                                                                                         'name': 'Hip-Hop/Rap'},
                                                                               'primary': True,
                                                                               'segment': {'id': 'KZFzniwnSyZfZ7v7nJ',
                                                                                           'name': 'Music'},
                                                                               'subGenre': {'id': 'KZazBEonSMnZfZ7vkdA',
                                                                                            'name': 'Urban'},
                                                                               'subType': {'id': 'KZFzBErXgnZfZ7vAd7',
                                                                                           'name': 'Musician'},
                                                                               'type': {'id': 'KZAyXgnZfZ7v7la',
                                                                                        'name': 'Individual'}}],
                                                          'externalLinks': {'spotify': [{'url': 'https://open.spotify.com/artist/3nFkdlSjzX9mRTtwJOzDYB'}],
                                                                            'twitter': [{'url': '@JayZ'}]},
                                                          'id': 'K8vZ9171Qi7',
                                                          'images': [{'fallback': False,
                                                                      'height': 360,
                                                                      'ratio': '16_9',
                                                                      'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_RETINA_PORTRAIT_16_9.jpg',
                                                                      'width': 640},
                                                                     {'fallback': False,
                                                                      'height': 225,
                                                                      'ratio': '4_3',
                                                                      'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_CUSTOM.jpg',
                                                                      'width': 305},
                                                                     {'fallback': False,
                                                                      'height': 1365,
                                                                      'ratio': '16_9',
                                                                      'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_SOURCE',
                                                                      'width': 2426},
                                                                     {'fallback': False,
                                                                      'height': 683,
                                                                      'ratio': '3_2',
                                                                      'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_TABLET_LANDSCAPE_3_2.jpg',
                                                                      'width': 1024},
                                                                     {'fallback': False,
                                                                      'height': 576,
                                                                      'ratio': '16_9',
                                                                      'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_TABLET_LANDSCAPE_16_9.jpg',
                                                                      'width': 1024},
                                                                     {'fallback': False,
                                                                      'height': 639,
                                                                      'ratio': '16_9',
                                                                      'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_RETINA_LANDSCAPE_16_9.jpg',
                                                                      'width': 1136},
                                                                     {'fallback': False,
                                                                      'height': 203,
                                                                      'ratio': '3_2',
                                                                      'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_ARTIST_PAGE_3_2.jpg',
                                                                      'width': 305},
                                                                     {'fallback': False,
                                                                      'height': 427,
                                                                      'ratio': '3_2',
                                                                      'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_RETINA_PORTRAIT_3_2.jpg',
                                                                      'width': 640},
                                                                     {'fallback': False,
                                                                      'height': 1152,
                                                                      'ratio': '16_9',
                                                                      'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_TABLET_LANDSCAPE_LARGE_16_9.jpg',
                                                                      'width': 2048},
                                                                     {'fallback': False,
                                                                      'height': 115,
                                                                      'ratio': '16_9',
                                                                      'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_EVENT_DETAIL_PAGE_16_9.jpg',
                                                                      'width': 205},
                                                                     {'fallback': False,
                                                                      'height': 56,
                                                                      'ratio': '16_9',
                                                                      'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_RECOMENDATION_16_9.jpg',
                                                                      'width': 100}],
                                                          'locale': 'en-us',
                                                          'name': 'JAŸ-Z',
                                                          'test': False,
                                                          'type': 'attraction',
                                                          'upcomingEvents': {'_filtered': 0,
                                                                             '_total': 6,
                                                                             'ticketmaster': 5,
                                                                             'trium': 1},
                                                          'url': 'https://www.ticketmaster.com/jayz-tickets/artist/781009'}],
                                         'venues': [{'_links': {'self': {'href': '/discovery/v2/venues/KovZ9177OxV?locale=en-us'}},
                                                     'ada': {'adaCustomCopy': 'Accessible '
                                                                              'tickets '
                                                                              'at '
                                                                              'Tottenham '
                                                                              'Hotspur '
                                                                              'Stadium '
                                                                              'are '
                                                                              'sold '
                                                                              'by '
                                                                              'the '
                                                                              'venue, '
                                                                              'including '
                                                                              'all '
                                                                              'presale '
                                                                              'tickets. \n'
                                                                              '\n'
                                                                              'To '
                                                                              'help '
                                                                              'plan '
                                                                              'your '
                                                                              'visit, '
                                                                              'Accessibility '
                                                                              'information '
                                                                              'can '
                                                                              'be '
                                                                              'found '
                                                                              'on '
                                                                              'the '
                                                                              'venue '
                                                                              'using '
                                                                              'the '
                                                                              'below '
                                                                              'URL:\n'
                                                                              'https://www.tottenhamhotspurstadium.com/plan-your-visit/accessibility/ '
                                                                              '(copy '
                                                                              'to '
                                                                              'browser)\n'
                                                                              '\n'
                                                                              '\n'
                                                                              '\n',
                                                             'adaHours': 'https://www.tottenhamhotspurstadium.com/plan-your-visit/accessibility/ '
                                                                         '(copy '
                                                                         'to '
                                                                         'browser)',
                                                             'adaPhones': 'https://www.tottenhamhotspurstadium.com/plan-your-visit/accessibility/ '
                                                                          '(copy '
                                                                          'to '
                                                                          'browser)'},
                                                     'address': {'line1': '782 '
                                                                          'High '
                                                                          'Rd'},
                                                     'city': {'name': 'London'},
                                                     'country': {'countryCode': 'GB',
                                                                 'name': 'Great '
                                                                         'Britain'},
                                                     'dmas': [{'id': 601}],
                                                     'id': 'KovZ9177OxV',
                                                     'locale': 'en-us',
                                                     'location': {'latitude': '51.60081900',
                                                                  'longitude': '-0.06787000'},
                                                     'markets': [{'id': '201',
                                                                  'name': 'All '
                                                                          'of '
                                                                          'United '
                                                                          'Kingdom'}],
                                                     'name': 'Tottenham '
                                                             'Hotspur Stadium',
                                                     'postalCode': 'N17 0BX',
                                                     'test': False,
                                                     'timezone': 'Europe/London',
                                                     'type': 'venue',
                                                     'upcomingEvents': {'_filtered': 0,
                                                                        '_total': 10,
                                                                        'ticketmaster': 10},
                                                     'url': 'https://www.ticketmaster.co.uk/tottenham-hotspur-stadium-tickets-london/venue/434396'}]},
                           '_links': {'attractions': [{'href': '/discovery/v2/attractions/K8vZ9171Qi7?locale=en-us'}],
                                      'self': {'href': '/discovery/v2/events/17u8v0G6CksBAD4?locale=en-us'},
                                      'venues': [{'href': '/discovery/v2/venues/KovZ9177OxV?locale=en-us'}]},
                           'accessibility': {'info': 'Accessible Areas - '
                                                     'Wheelchair and Ambulant '
                                                     'Seating Requirements for '
                                                     'this event are sold by '
                                                     'Tottenham Hotspur '
                                                     'Stadium via their site '
                                                     'click here',
                                             'url': 'https://www.eticketing.co.uk/tottenhamhotspurstadium/EDP/Event/Index/127?spell=b809bd91-0cf6-41af-966b-45e6f82a3ed1',
                                             'urlText': 'Click here to visit '
                                                        'their site'},
                           'ageRestrictions': {'legalAgeEnforced': False},
                           'classifications': [{'family': False,
                                                'genre': {'id': 'KnvZfZ7vAv1',
                                                          'name': 'Hip-Hop/Rap'},
                                                'primary': True,
                                                'segment': {'id': 'KZFzniwnSyZfZ7v7nJ',
                                                            'name': 'Music'},
                                                'subGenre': {'id': 'KZazBEonSMnZfZ7vaEI',
                                                             'name': 'Trap'},
                                                'subType': {'id': 'KZFzBErXgnZfZ7v7lJ',
                                                            'name': 'Undefined'},
                                                'type': {'id': 'KZAyXgnZfZ7v7nI',
                                                         'name': 'Undefined'}}],
                           'dates': {'spanMultipleDays': False,
                                     'start': {'dateTBA': False,
                                               'dateTBD': False,
                                               'dateTime': '2026-09-04T16:00:00Z',
                                               'localDate': '2026-09-04',
                                               'localTime': '17:00:00',
                                               'noSpecificTime': False,
                                               'timeTBA': False},
                                     'status': {'code': 'offsale'},
                                     'timezone': 'Europe/London'},
                           'id': '17u8v0G6CksBAD4',
                           'images': [{'fallback': False,
                                       'height': 360,
                                       'ratio': '16_9',
                                       'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_RETINA_PORTRAIT_16_9.jpg',
                                       'width': 640},
                                      {'fallback': False,
                                       'height': 225,
                                       'ratio': '4_3',
                                       'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_CUSTOM.jpg',
                                       'width': 305},
                                      {'fallback': False,
                                       'height': 1365,
                                       'ratio': '16_9',
                                       'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_SOURCE',
                                       'width': 2426},
                                      {'fallback': False,
                                       'height': 683,
                                       'ratio': '3_2',
                                       'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_TABLET_LANDSCAPE_3_2.jpg',
                                       'width': 1024},
                                      {'fallback': False,
                                       'height': 576,
                                       'ratio': '16_9',
                                       'url': 'https://s1.ticketm.net/dam/a/4ec/1e6d3beb-bfd6-4d63-a460-63cb6125f4ec_TABLET_LANDSCAPE_16_9.jpg',
                                       'width': 1024},
                                      {'fallback': False,
                                       'height': 639,
                                       'ratio': '16_9',

In [12]:
# Creating the dataframe df

events = data['_embedded']['events']  # your list of 20 dicts

df = pd.json_normalize(events)
df.head()

,name,type,id,test,url,locale,images,classifications,promoters,pleaseNote,...,seatmap.staticUrl,accessibility.ticketLimit,linkMoreInfo.descriptions.ca-es,linkMoreInfo.descriptions.de-de,linkMoreInfo.descriptions.en-es,linkMoreInfo.descriptions.en-us,linkMoreInfo.descriptions.en-de,linkMoreInfo.descriptions.es-es,linkMoreInfo.descriptions.en-gb,linkMoreInfo.url
0,JAY-Z - 30,event,17u8v0G6CksBAD4,False,https://www.ticketmaster.co.uk/jayz-30-london-...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....","[{'primary': True, 'segment': {'id': 'KZFzniwn...","[{'id': '6678', 'name': 'LIVE NATION UK FOR AR...",There will be no admittance for children under...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,The World of Hans Zimmer - a New Dimension,event,G5vHZbJBpZsXN,False,https://www.ticketmaster.co.uk/the-world-of-ha...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....","[{'primary': True, 'segment': {'id': 'KZFzniwn...","[{'id': '6145', 'name': 'KMJ ENTERTAINMENT LTD...",Under 14s must be accompanied by an adult over...,...,https://s1.ticketm.net/uk/tmimages/venue/maps/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,The World of Hans Zimmer - a New Dimension,event,1AeGZbJGkB_ZZUA,False,https://www.ticketmaster.co.uk/the-world-of-ha...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....","[{'primary': True, 'segment': {'id': 'KZFzniwn...","[{'id': '6145', 'name': 'KMJ ENTERTAINMENT LTD...",Under 14s must be accompanied by an adult over...,...,https://s1.ticketm.net/uk/tmimages/venue/maps/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,The Holiday in Concert - Film with Live Orchestra,event,G5vHZ_aedKoux,False,https://www.ticketmaster.co.uk/the-holiday-in-...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....","[{'primary': True, 'segment': {'id': 'KZFzniwn...","[{'id': '3013', 'name': 'SENBLA LIMITED', 'des...",Under 16s must be accompanied by an adult over...,...,https://s1.ticketm.net/uk/tmimages/venue/maps/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,The Holiday - Film With Live Orchestra,event,1AdbZ_kGkRuAbPW,False,https://www.ticketmaster.co.uk/the-holiday-fil...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....","[{'primary': True, 'segment': {'id': 'KZFzniwn...","[{'id': '3013', 'name': 'SENBLA LIMITED', 'des...",Over 12s only. Under 14s must be accompanied b...,...,https://s1.ticketm.net/uk/tmimages/venue/maps/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 59 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   name                                   20 non-null     object
 1   type                                   20 non-null     object
 2   id                                     20 non-null     object
 3   test                                   20 non-null     bool
 4   url                                    20 non-null     object
 5   locale                                 20 non-null     object
 6   images                                 20 non-null     object
 7   classifications                        20 non-null     object
 8   promoters                              20 non-null     object
 9   pleaseNote                             20 non-null     object
 10  products                               1 non-null      object
 11  nameOrigin                             20 non-null     object
 12  sales.public.startDateTime             20 non-null     object
 13  sales.public.startTBD                  20 non-null     bool
 14  sales.public.startTBA                  20 non-null     bool
 15  sales.public.endDateTime               20 non-null     object
 16  sales.presales                         18 non-null     object
 17  dates.start.localDate                  20 non-null     object
 18  dates.start.localTime                  20 non-null     object
 19  dates.start.dateTime                   20 non-null     object
 20  dates.start.dateTBD                    20 non-null     bool
 21  dates.start.dateTBA                    20 non-null     bool
 22  dates.start.timeTBA                    20 non-null     bool
 23  dates.start.noSpecificTime             20 non-null     bool
 24  dates.timezone                         20 non-null     object
 25  dates.status.code                      20 non-null     object
 26  dates.spanMultipleDays                 20 non-null     bool
 27  promoter.id                            20 non-null     object
 28  promoter.name                          20 non-null     object
 29  promoter.description                   20 non-null     object
 30  accessibility.info                     2 non-null      object
 31  accessibility.url                      2 non-null      object
 32  accessibility.urlText                  2 non-null      object
 33  ticketLimit.info                       18 non-null     object
 34  ageRestrictions.legalAgeEnforced       20 non-null     bool
 35  ticketing.safeTix.enabled              20 non-null     bool
 36  ticketing.allInclusivePricing.enabled  20 non-null     bool
 37  ticketTextLines.en-gb.line6            6 non-null      object
 38  ticketTextLines.en-gb.line5            6 non-null      object
 39  ticketTextLines.en-gb.line4            6 non-null      object
 40  ticketTextLines.en-gb.line3            6 non-null      object
 41  ticketTextLines.en-gb.line2            6 non-null      object
 42  ticketTextLines.en-gb.line1            6 non-null      object
 43  _links.self.href                       20 non-null     object
 44  _links.attractions                     20 non-null     object
 45  _links.venues                          20 non-null     object
 46  _embedded.venues                       20 non-null     object
 47  _embedded.attractions                  20 non-null     object
 48  info                                   4 non-null      object
 49  seatmap.staticUrl                      19 non-null     object
 50  accessibility.ticketLimit              2 non-null      float64
 51  linkMoreInfo.descriptions.ca-es        2 non-null      object
 52  linkMoreInfo.descriptions.de-de        2 non-null      object
 53  linkMoreInfo.descriptions.en-es        2 non-null      object
 54  linkMoreInfo.descriptions.en-us        2 non-null      object
 55  linkMoreInfo.descriptions.en-de        2 non-null      object
 56  linkMoreInfo.descriptions.es-es        2 non-null      object
 57  linkMoreInfo.descriptions.en-gb        2 non-null      object
 58  linkMoreInfo.url                       2 non-null      object
dtypes: bool(11), float64(1), object(47)
memory usage: 7.8+ KB

Pagination required to pull data from all the pages

In [17]:
def generate_month_chunks(year, months):
    chunks = []
    for month in months:
        start = pd.Timestamp(year=year, month=month, day=1)
        end = (start + pd.offsets.MonthEnd(1)).replace(hour=23, minute=59, second=59)
        chunks.append((
            start.strftime("%Y-%m-%dT%H:%M:%SZ"),
            end.strftime("%Y-%m-%dT%H:%M:%SZ")
        ))
    return chunks

date_chunks = generate_month_chunks(2026, months=[6, 7, 8])  # June, July, August
print(date_chunks)

[('2026-06-01T00:00:00Z', '2026-06-30T23:59:59Z'), ('2026-07-01T00:00:00Z', '2026-07-31T23:59:59Z'), ('2026-08-01T00:00:00Z', '2026-08-31T23:59:59Z')]

In [20]:
def fetch_page(page_number, start_date, end_date):
    params = {
        "apikey": API_KEY,
        "countryCode": "GB",
        "classificationName": "Music",
        "startDateTime": start_date,
        "endDateTime": end_date,
        "sort": "date,asc",
        "size": 200,
        "page": page_number
    }
    response = requests.get(BASE_URL, params=params)

    if response.status_code == 429:
        print("Rate limited — waiting 5s...")
        time.sleep(5)
        return fetch_page(page_number, start_date, end_date)

    response.raise_for_status()
    return response.json()

In [21]:
def fetch_all_pages_for_range(start_date, end_date):
    all_pages = []
    first_page = fetch_page(0, start_date, end_date)
    all_pages.append(first_page)

    total_pages = first_page.get("page", {}).get("totalPages", 1)
    total_elements = first_page.get("page", {}).get("totalElements", 0)
    print(f"  {start_date[:7]}: {total_elements} events across {total_pages} pages")

    max_pages = total_pages  # no cap — pull everything for a 3-month window

    for page_num in range(1, max_pages):
        time.sleep(0.25)
        page_data = fetch_page(page_num, start_date, end_date)
        all_pages.append(page_data)

    return all_pages

In [27]:
all_events = []
all_pages_flat = []
BASE_URL = "https://app.ticketmaster.com/discovery/v2/events.json"

for start_date, end_date in date_chunks:
    pages = fetch_all_pages_for_range(start_date, end_date)
    all_pages_flat.extend(pages)
    for page in pages:
        all_events.extend(page.get("_embedded", {}).get("events", []))
    time.sleep(0.5)

print(f"\nTotal events collected: {len(all_events)}")

  2026-06: 1 events across 1 pages
  2026-07: 988 events across 5 pages
  2026-08: 1101 events across 6 pages

Total events collected: 2090

In [28]:
RAW_DIR = Path("data/raw")
RAW_DIR.mkdir(parents=True, exist_ok=True)
# now save raw
for i, page in enumerate(all_pages_flat):
    with open(RAW_DIR / f"uk_music_jun_aug_page{i}.json", "w") as f:
        json.dump(page, f)

In [29]:
from collections import Counter

month_counts = Counter()
for event in all_events:
    date = event.get("dates", {}).get("start", {}).get("localDate")
    if date:
        month_counts[date[:7]] += 1

for month in sorted(month_counts):
    print(month, month_counts[month])

2026-06 2
2026-07 995
2026-08 1093

In [30]:
event_ids = [e.get('id') for e in all_events]
print(f"Total events: {len(event_ids)}")
print(f"Unique event IDs: {len(set(event_ids))}")

Total events: 2090
Unique event IDs: 2081

In [31]:
# confirming the pagination worked
response = requests.get(
    "https://app.ticketmaster.com/discovery/v2/events.json",
    params={
        "apikey": API_KEY,
        "countryCode": "GB",
        "classificationName": "Music",
        "startDateTime": "2026-07-01T00:00:00Z",
        "endDateTime": "2026-08-31T23:59:59Z",
        "size": 200,
        "page": 0
    }
)

data = response.json()
page_info = data.get("page", {})

print(f"Total elements matched: {page_info.get('totalElements')}")
print(f"Total pages (at size=200): {page_info.get('totalPages')}")

Total elements matched: 2081
Total pages (at size=200): 11

In [32]:
# 1. Does the count match what totalElements said we should expect?
print(f"Expected total (from API metadata): 2081")
print(f"Actually collected in all_events: {len(all_events)}")

# 2. Did we genuinely make 11 separate page requests, not just 1?
print(f"Number of raw pages fetched: {len(all_pages_flat)}")

# 3. Check each page's own reported page number, to confirm they're actually different pages, not the same one repeated
for page in all_pages_flat:
    page_num = page.get("page", {}).get("number")
    events_in_page = len(page.get("_embedded", {}).get("events", []))
    print(f"Page {page_num}: {events_in_page} events")

Expected total (from API metadata): 2081
Actually collected in all_events: 2090
Number of raw pages fetched: 12
Page 0: 1 events
Page 0: 200 events
Page 1: 200 events
Page 2: 200 events
Page 3: 200 events
Page 4: 188 events
Page 0: 200 events
Page 1: 200 events
Page 2: 200 events
Page 3: 200 events
Page 4: 200 events
Page 5: 101 events

Now lets create our df

In [33]:
# Build df from the real paginated pull, not the old 20-event test
df = pd.json_normalize(all_events)
print(df.shape)
df.head()

(2090, 81)

,name,type,id,test,description,url,locale,images,classifications,nameOrigin,...,dates.end.localDate,ageRestrictions.ageRuleDescription,attractionGroups.major.description,attractionGroups.major.descriptions.tm-df,attractionGroups.major.descriptions.en-gb,attractionGroups.minor.id,attractionGroups.minor.name,dates.initialStartDate.localDate,dates.initialStartDate.localTime,dates.initialStartDate.dateTime
0,EVERYWHERE AT ONCE: Dewin,event,LvZ18QxAj1bZeL8vGSGnc,False,Everywhere At Once powered by The National Lot...,https://www.universe.com/events/everywhere-at-...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....","[{'segment': {'id': 'KZFzniwnSyZfZ7v7nJ', 'nam...",custom,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,EVERYWHERE AT ONCE: Dewin,event,LvZ18QxAj1bZeL8vGSGnc,False,Everywhere At Once powered by The National Lot...,https://www.universe.com/events/everywhere-at-...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....","[{'segment': {'id': 'KZFzniwnSyZfZ7v7nJ', 'nam...",custom,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Orchestral Qawwali Project,event,G5vHZ_dQ2CoCm,False,NaN,https://www.ticketmaster.co.uk/orchestral-qaww...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....","[{'primary': True, 'segment': {'id': 'KZFzniwn...",custom,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,The Maccabees,event,G5vHZbM3j8P-r,False,NaN,https://www.ticketmaster.co.uk/the-maccabees-l...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",primaryAttraction,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Billy Ocean with very special guest Marti Pellow,event,G5vHZbVxTtI6b,False,NaN,https://www.ticketmaster.co.uk/billy-ocean-wit...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",custom,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
print(df['name'].nunique()) # We have 1459 unique names - pagination successful

1459

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2090 entries, 0 to 2089
Data columns (total 81 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   name                                       2090 non-null   object
 1   type                                       2090 non-null   object
 2   id                                         2090 non-null   object
 3   test                                       2090 non-null   bool
 4   description                                823 non-null    object
 5   url                                        2090 non-null   object
 6   locale                                     2090 non-null   object
 7   images                                     2090 non-null   object
 8   classifications                            2090 non-null   object
 9   nameOrigin                                 2090 non-null   object
 10  sales.public.startDateTime                 2028 non-null   object
 11  sales.public.startTBD                      2090 non-null   bool
 12  sales.public.startTBA                      2090 non-null   bool
 13  sales.public.endDateTime                   2028 non-null   object
 14  dates.access.startDateTime                 823 non-null    object
 15  dates.access.startApproximate              823 non-null    object
 16  dates.access.endDateTime                   823 non-null    object
 17  dates.access.endApproximate                823 non-null    object
 18  dates.start.localDate                      2090 non-null   object
 19  dates.start.localTime                      1939 non-null   object
 20  dates.start.dateTime                       1939 non-null   object
 21  dates.start.dateTBD                        2090 non-null   bool
 22  dates.start.dateTBA                        2090 non-null   bool
 23  dates.start.timeTBA                        2090 non-null   bool
 24  dates.start.noSpecificTime                 2090 non-null   bool
 25  dates.end.localTime                        823 non-null    object
 26  dates.end.dateTime                         823 non-null    object
 27  dates.end.approximate                      973 non-null    object
 28  dates.end.noSpecificTime                   973 non-null    object
 29  dates.timezone                             2090 non-null   object
 30  dates.status.code                          2090 non-null   object
 31  dates.spanMultipleDays                     2090 non-null   bool
 32  _links.self.href                           2090 non-null   object
 33  _links.attractions                         2010 non-null   object
 34  _links.venues                              2090 non-null   object
 35  _embedded.venues                           2090 non-null   object
 36  _embedded.attractions                      2010 non-null   object
 37  promoters                                  947 non-null    object
 38  pleaseNote                                 929 non-null    object
 39  promoter.id                                947 non-null    object
 40  promoter.name                              947 non-null    object
 41  promoter.description                       947 non-null    object
 42  accessibility.ticketLimit                  185 non-null    float64
 43  ageRestrictions.legalAgeEnforced           1266 non-null   object
 44  ticketing.safeTix.enabled                  1266 non-null   object
 45  ticketing.allInclusivePricing.enabled      1266 non-null   object
 46  ticketTextLines.en-gb.line6                609 non-null    object
 47  ticketTextLines.en-gb.line5                609 non-null    object
 48  ticketTextLines.en-gb.line4                609 non-null    object
 49  ticketTextLines.en-gb.line3                609 non-null    object
 50  ticketTextLines.en-gb.line2                609 non-null    object
 51  ticketTextLines.en-gb.line1                609 non-null    object
 52  ticketLimit.info                           909 non-null    object
 53  info                                       633 non-null    object
 54  sales.presales                             477 non-null    object
 55  seatmap.staticUrl                          650 non-null    object
 56  linkMoreInfo.descriptions.ca-es            200 non-null    object
 57  linkMoreInfo.descriptions.de-de            200 non-null    object
 58  linkMoreInfo.descriptions.en-es            200 non-null    object
 59  linkMoreInfo.descriptions.en-us            200 non-null    object
 60  linkMoreInfo.descriptions.en-de            200 non-null    object
 61  linkMoreInfo.descriptions.es-es            200 non-null    object
 62  linkMoreInfo.descriptions.en-gb            200 non-null    object
 63  linkMoreInfo.url                           200 non-null    object
 64  accessibility.info                         155 non-null    object
 65  accessibility.url                          106 non-null    object
 66  accessibility.urlText                      106 non-null    object
 67  products                                   43 non-null     object
 68  attractionGroups.attractionId              171 non-null    object
 69  attractionGroups.major.id                  171 non-null    object
 70  attractionGroups.major.name                171 non-null    object
 71  dates.end.localDate                        150 non-null    object
 72  ageRestrictions.ageRuleDescription         7 non-null      object
 73  attractionGroups.major.description         27 non-null     object
 74  attractionGroups.major.descriptions.tm-df  27 non-null     object
 75  attractionGroups.major.descriptions.en-gb  27 non-null     object
 76  attractionGroups.minor.id                  67 non-null     object
 77  attractionGroups.minor.name                67 non-null     object
 78  dates.initialStartDate.localDate           1 non-null      object
 79  dates.initialStartDate.localTime           1 non-null      object
 80  dates.initialStartDate.dateTime            1 non-null      object
dtypes: bool(8), float64(1), object(72)
memory usage: 1.2+ MB

In [42]:
# null value check
def null_vals(dataframe):
    """
    Show both number of nulls and the percentage of nulls in the whole column across a Pandas dataframe.
    """
    null_vals = dataframe.isnull().sum() # How many nulls in each column
    total_cnt = len(dataframe) # Total entries in the dataframe
    null_vals = pd.DataFrame(null_vals,columns=['null']) # Put the number of nulls in a single dataframe
    null_vals['percent'] = round((null_vals['null']/total_cnt)*100,3) # Round how many nulls are there, as %, of the df
    
    return null_vals.sort_values('percent', ascending=False) # Ordered from MOST to LEAST nulls
    
print(null_vals(df).to_string())

                                           null  percent
dates.initialStartDate.dateTime            2089   99.952
dates.initialStartDate.localTime           2089   99.952
dates.initialStartDate.localDate           2089   99.952
ageRestrictions.ageRuleDescription         2083   99.665
attractionGroups.major.descriptions.en-gb  2063   98.708
attractionGroups.major.descriptions.tm-df  2063   98.708
attractionGroups.major.description         2063   98.708
products                                   2047   97.943
attractionGroups.minor.name                2023   96.794
attractionGroups.minor.id                  2023   96.794
accessibility.url                          1984   94.928
accessibility.urlText                      1984   94.928
dates.end.localDate                        1940   92.823
accessibility.info                         1935   92.584
attractionGroups.attractionId              1919   91.818
attractionGroups.major.id                  1919   91.818
attractionGroups.major.name                1919   91.818
accessibility.ticketLimit                  1905   91.148
linkMoreInfo.descriptions.en-us            1890   90.431
linkMoreInfo.descriptions.en-gb            1890   90.431
linkMoreInfo.descriptions.ca-es            1890   90.431
linkMoreInfo.descriptions.en-de            1890   90.431
linkMoreInfo.descriptions.es-es            1890   90.431
linkMoreInfo.descriptions.en-es            1890   90.431
linkMoreInfo.url                           1890   90.431
linkMoreInfo.descriptions.de-de            1890   90.431
sales.presales                             1613   77.177
ticketTextLines.en-gb.line1                1481   70.861
ticketTextLines.en-gb.line3                1481   70.861
ticketTextLines.en-gb.line4                1481   70.861
ticketTextLines.en-gb.line2                1481   70.861
ticketTextLines.en-gb.line5                1481   70.861
ticketTextLines.en-gb.line6                1481   70.861
info                                       1457   69.713
seatmap.staticUrl                          1440   68.900
dates.access.startApproximate              1267   60.622
dates.end.dateTime                         1267   60.622
dates.end.localTime                        1267   60.622
description                                1267   60.622
dates.access.endApproximate                1267   60.622
dates.access.endDateTime                   1267   60.622
dates.access.startDateTime                 1267   60.622
ticketLimit.info                           1181   56.507
pleaseNote                                 1161   55.550
promoter.name                              1143   54.689
promoter.description                       1143   54.689
promoter.id                                1143   54.689
promoters                                  1143   54.689
dates.end.noSpecificTime                   1117   53.445
dates.end.approximate                      1117   53.445
ticketing.allInclusivePricing.enabled       824   39.426
ageRestrictions.legalAgeEnforced            824   39.426
ticketing.safeTix.enabled                   824   39.426
dates.start.dateTime                        151    7.225
dates.start.localTime                       151    7.225
_links.attractions                           80    3.828
_embedded.attractions                        80    3.828
sales.public.endDateTime                     62    2.967
sales.public.startDateTime                   62    2.967
images                                        0    0.000
classifications                               0    0.000
nameOrigin                                    0    0.000
url                                           0    0.000
test                                          0    0.000
sales.public.startTBD                         0    0.000
sales.public.startTBA                         0    0.000
id                                            0    0.000
locale                                        0    0.000
dates.start.timeTBA                           0    0.000
dates.start.localDate                         0    0.000
dates.start.dateTBD                           0    0.000
dates.start.dateTBA                           0    0.000
dates.start.noSpecificTime                    0    0.000
dates.timezone                                0    0.000
dates.status.code                             0    0.000
dates.spanMultipleDays                        0    0.000
_links.self.href                              0    0.000
_links.venues                                 0    0.000
_embedded.venues                              0    0.000
type                                          0    0.000
name                                          0    0.000

In [44]:
# check to see which columns are nested 

nested_cols = []

for col in df.columns:
    non_null = df[col].dropna()
    if len(non_null) == 0:
        continue
    sample = non_null.iloc[0]
    if isinstance(sample, (list, dict)):
        nested_cols.append(col)

print(nested_cols)

['images', 'classifications', '_links.attractions', '_links.venues', '_embedded.venues', '_embedded.attractions', 'promoters', 'sales.presales', 'products']

In [73]:
# Lets explore the nested columns to see if worth unravelling

df['images'].iloc[0]

[{'ratio': '16_9',
  'url': 'https://s1.ticketm.net/dam/c/797/5e693c26-2881-4776-8f0c-3aa94bfa3797_106511_RETINA_PORTRAIT_16_9.jpg',
  'width': 640,
  'height': 360,
  'fallback': True},
 {'ratio': '4_3',
  'url': 'https://images.universe.com/d3a8bc1e-594f-4671-88c2-fdc233e87e5d/-/format/jpeg/-/scale_crop/305x225/center/-/progressive/yes/-/inline/yes/',
  'width': 305,
  'height': 225,
  'fallback': False},
 {'ratio': '16_9',
  'url': 'https://s1.ticketm.net/dam/c/f50/96fa13be-e395-429b-8558-a51bb9054f50_105951_TABLET_LANDSCAPE_LARGE_16_9.jpg',
  'width': 2048,
  'height': 1152,
  'fallback': True},
 {'ratio': '3_2',
  'url': 'https://images.universe.com/d3a8bc1e-594f-4671-88c2-fdc233e87e5d/-/format/jpeg/-/scale_crop/305x203/center/-/progressive/yes/-/inline/yes/',
  'width': 305,
  'height': 203,
  'fallback': False},
 {'ratio': '16_9',
  'url': 'https://s1.ticketm.net/dam/c/797/5e693c26-2881-4776-8f0c-3aa94bfa3797_106511_RECOMENDATION_16_9.jpg',
  'width': 100,
  'height': 56,
  'fallback': True},
 {'ratio': '3_2',
  'url': 'https://images.universe.com/d3a8bc1e-594f-4671-88c2-fdc233e87e5d/-/format/jpeg/-/scale_crop/1024x683/center/-/progressive/yes/-/inline/yes/',
  'width': 1024,
  'height': 683,
  'fallback': False},
 {'ratio': '16_9',
  'url': 'https://images.universe.com/d3a8bc1e-594f-4671-88c2-fdc233e87e5d/-/format/jpeg/-/scale_crop/1024x576/center/-/progressive/yes/-/inline/yes/',
  'width': 1024,
  'height': 576,
  'fallback': False},
 {'ratio': '3_2',
  'url': 'https://images.universe.com/d3a8bc1e-594f-4671-88c2-fdc233e87e5d/-/format/jpeg/-/scale_crop/640x427/center/-/progressive/yes/-/inline/yes/',
  'width': 640,
  'height': 427,
  'fallback': False},
 {'ratio': '16_9',
  'url': 'https://s1.ticketm.net/dam/c/797/5e693c26-2881-4776-8f0c-3aa94bfa3797_106511_RETINA_LANDSCAPE_16_9.jpg',
  'width': 1136,
  'height': 639,
  'fallback': True},
 {'ratio': '16_9',
  'url': 'https://s1.ticketm.net/dam/c/797/5e693c26-2881-4776-8f0c-3aa94bfa3797_106511_EVENT_DETAIL_PAGE_16_9.jpg',
  'width': 205,
  'height': 115,
  'fallback': True}]

Creating seperate tables for nested columns

In [164]:
def build_nested_table(df, id_col, nested_col):
    """
    Turns a nested list-of-dicts (or single dict) column into its own table,
    one row per item, linked back to the parent via id_col.
    Unwraps ONE level of nested dicts (e.g. genre: {id, name} -> genre_id, genre_name).
    Lists nested inside items are skipped (too complex for a flat row).
    """
    rows = []
    for _, row in df.iterrows():
        parent_id = row[id_col]
        value = row.get(nested_col)
        if value is None:
            continue
        items = value if isinstance(value, list) else [value]
        for item in items:
            if not isinstance(item, dict):
                continue
            flat_item = {f"event_{id_col}": parent_id}   # renamed to avoid collision
            for key, val in item.items():
                if isinstance(val, dict):
                    for subkey, subval in val.items():
                        flat_item[f"{key}_{subkey}"] = subval
                elif isinstance(val, list):
                    continue
                else:
                    flat_item[key] = val   # venue's own 'id' now safely separate
            rows.append(flat_item)
    return pd.DataFrame(rows)

In [70]:
df_images = build_nested_table(df, id_col='id', nested_col='images')
df_classifications = build_nested_table(df, id_col='id', nested_col='classifications')
df_venues = build_nested_table(df_og, id_col='id', nested_col='_embedded.venues')
df_attractions = build_nested_table(df, id_col='id', nested_col='_embedded.attractions')
df_promoters = build_nested_table(df, id_col='id', nested_col='promoters')

print("images:", df_images.shape, df_images.columns.tolist())
print("classifications:", df_classifications.shape, df_classifications.columns.tolist())
print("venues:", df_venues.shape, df_venues.columns.tolist())
print("attractions:", df_attractions.shape, df_attractions.columns.tolist())
print("promoters:", df_promoters.shape, df_promoters.columns.tolist())

images: (22683, 7) ['id', 'ratio', 'url', 'width', 'height', 'fallback', 'attribution']
classifications: (2090, 13) ['id', 'segment_id', 'segment_name', 'genre_id', 'genre_name', 'subGenre_id', 'subGenre_name', 'family', 'primary', 'type_id', 'type_name', 'subType_id', 'subType_name']
venues: (2090, 35) ['id', 'name', 'type', 'test', 'url', 'locale', 'postalCode', 'timezone', 'city_name', 'country_name', 'country_countryCode', 'address_line1', 'location_longitude', 'location_latitude', 'upcomingEvents_universe', 'upcomingEvents__total', 'upcomingEvents__filtered', '_links_self', 'address_line2', 'upcomingEvents_ticketmaster', 'ada_adaPhones', 'ada_adaCustomCopy', 'ada_adaHours', 'boxOfficeInfo_openHoursDetail', 'boxOfficeInfo_willCallDetail', 'parkingDetail', 'accessibleSeatingDetail', 'generalInfo_generalRule', 'generalInfo_childRule', 'boxOfficeInfo_acceptedPaymentDetail', 'boxOfficeInfo_phoneNumberDetail', 'social_twitter', 'upcomingEvents_tmr', 'upcomingEvents_tmc', 'upcomingEvents_sportxr-uk_asmglobalmanchester']
attractions: (5040, 53) ['id', 'name', 'type', 'test', 'url', 'locale', 'externalLinks_spotify', 'externalLinks_instagram', 'upcomingEvents__total', 'upcomingEvents__filtered', '_links_self', 'upcomingEvents_universe', 'upcomingEvents_ticketmaster', 'externalLinks_youtube', 'externalLinks_twitter', 'externalLinks_itunes', 'externalLinks_wiki', 'externalLinks_facebook', 'externalLinks_musicbrainz', 'externalLinks_homepage', 'externalLinks_lastfm', 'upcomingEvents_mfx-fi', 'upcomingEvents_mticket', 'externalLinks_bandcamp', 'externalLinks_tiktok', 'externalLinks_soundcloud', 'upcomingEvents_mfx-nl', 'upcomingEvents_mfx-de', 'upcomingEvents_mfx-cz', 'upcomingEvents_mfx-dk', 'upcomingEvents_mfx-be', 'upcomingEvents_mfx-ch', 'upcomingEvents_trium', 'upcomingEvents_tmr', 'upcomingEvents_wts-tr', 'upcomingEvents_ticketweb', 'upcomingEvents_moshtix', 'draftStatus', 'upcomingEvents_mfx-no', 'upcomingEvents_mfx-se', 'upcomingEvents_mfx-it', 'upcomingEvents_mfx-at', 'upcomingEvents_mfx-es', 'upcomingEvents_mfx-pl', 'upcomingEvents_mfx-ae', 'upcomingEvents_crowder', 'upcomingEvents_ticketnet', 'upcomingEvents_tmc', 'upcomingEvents_tixcraft-sg', 'upcomingEvents_sportxr', 'upcomingEvents_quicket', 'upcomingEvents_mfx-za', 'upcomingEvents_sportxtr']
promoters: (1988, 3) ['id', 'name', 'description']

In [81]:
df_promoters.head()

,id,name,description
0,3251,CUFFE & TAYLOR EVENT MANAGEMENT,CUFFE & TAYLOR EVENT MANAGEMENT / NTL / GBR
1,3251,CUFFE & TAYLOR EVENT MANAGEMENT,CUFFE & TAYLOR EVENT MANAGEMENT / NTL / GBR
2,4132,LLANGOLLEN INTERNATIONAL MUSICAL EISTEDDFOD,LLANGOLLEN INTERNATIONAL MUSICAL EISTEDDFOD / ...
3,5279,S.J.M. LTD,S.J.M. LTD / NTL / GBR
4,5279,S.J.M. LTD,S.J.M. LTD / NTL / GBR

In [80]:
print(null_vals(df_promoters).to_string())

             null  percent
id              0      0.0
name            0      0.0
description     0      0.0

Creating df_og to represent our original df. We will be tweaking df though.

In [82]:
df_new = df.copy()

In [90]:
nested_cols_to_drop = ['images', 'classifications', '_embedded.venues', '_embedded.attractions', 'promoters']

df = df_new.drop(columns=nested_cols_to_drop, errors='ignore')
df_new.shape
df_new.head()

,name,type,id,test,description,url,locale,images,classifications,nameOrigin,...,dates.end.localDate,ageRestrictions.ageRuleDescription,attractionGroups.major.description,attractionGroups.major.descriptions.tm-df,attractionGroups.major.descriptions.en-gb,attractionGroups.minor.id,attractionGroups.minor.name,dates.initialStartDate.localDate,dates.initialStartDate.localTime,dates.initialStartDate.dateTime
0,EVERYWHERE AT ONCE: Dewin,event,LvZ18QxAj1bZeL8vGSGnc,False,Everywhere At Once powered by The National Lot...,https://www.universe.com/events/everywhere-at-...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....","[{'segment': {'id': 'KZFzniwnSyZfZ7v7nJ', 'nam...",custom,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,EVERYWHERE AT ONCE: Dewin,event,LvZ18QxAj1bZeL8vGSGnc,False,Everywhere At Once powered by The National Lot...,https://www.universe.com/events/everywhere-at-...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....","[{'segment': {'id': 'KZFzniwnSyZfZ7v7nJ', 'nam...",custom,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Orchestral Qawwali Project,event,G5vHZ_dQ2CoCm,False,NaN,https://www.ticketmaster.co.uk/orchestral-qaww...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....","[{'primary': True, 'segment': {'id': 'KZFzniwn...",custom,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,The Maccabees,event,G5vHZbM3j8P-r,False,NaN,https://www.ticketmaster.co.uk/the-maccabees-l...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",primaryAttraction,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Billy Ocean with very special guest Marti Pellow,event,G5vHZbVxTtI6b,False,NaN,https://www.ticketmaster.co.uk/billy-ocean-wit...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",custom,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
df.head()

,name,type,id,test,description,url,locale,nameOrigin,sales.public.startDateTime,sales.public.startTBD,...,dates.end.localDate,ageRestrictions.ageRuleDescription,attractionGroups.major.description,attractionGroups.major.descriptions.tm-df,attractionGroups.major.descriptions.en-gb,attractionGroups.minor.id,attractionGroups.minor.name,dates.initialStartDate.localDate,dates.initialStartDate.localTime,dates.initialStartDate.dateTime
0,EVERYWHERE AT ONCE: Dewin,event,LvZ18QxAj1bZeL8vGSGnc,False,Everywhere At Once powered by The National Lot...,https://www.universe.com/events/everywhere-at-...,en-us,custom,2026-06-04T11:06:18Z,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,EVERYWHERE AT ONCE: Dewin,event,LvZ18QxAj1bZeL8vGSGnc,False,Everywhere At Once powered by The National Lot...,https://www.universe.com/events/everywhere-at-...,en-us,custom,2026-06-04T11:06:18Z,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Orchestral Qawwali Project,event,G5vHZ_dQ2CoCm,False,NaN,https://www.ticketmaster.co.uk/orchestral-qaww...,en-us,custom,2026-01-23T15:00:00Z,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,The Maccabees,event,G5vHZbM3j8P-r,False,NaN,https://www.ticketmaster.co.uk/the-maccabees-l...,en-us,primaryAttraction,2025-11-28T10:00:00Z,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Billy Ocean with very special guest Marti Pellow,event,G5vHZbVxTtI6b,False,NaN,https://www.ticketmaster.co.uk/billy-ocean-wit...,en-us,custom,2025-10-17T09:00:00Z,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
# confirming column names
print(df_classifications.columns.tolist())
print(df_venues.columns.tolist())
pprint(df_attractions.columns.tolist())

['id', 'segment_id', 'segment_name', 'genre_id', 'genre_name', 'subGenre_id', 'subGenre_name', 'family', 'primary', 'type_id', 'type_name', 'subType_id', 'subType_name']
['id', 'name', 'type', 'test', 'url', 'locale', 'postalCode', 'timezone', 'city_name', 'country_name', 'country_countryCode', 'address_line1', 'location_longitude', 'location_latitude', 'upcomingEvents_universe', 'upcomingEvents__total', 'upcomingEvents__filtered', '_links_self', 'address_line2', 'upcomingEvents_ticketmaster', 'ada_adaPhones', 'ada_adaCustomCopy', 'ada_adaHours', 'boxOfficeInfo_openHoursDetail', 'boxOfficeInfo_willCallDetail', 'parkingDetail', 'accessibleSeatingDetail', 'generalInfo_generalRule', 'generalInfo_childRule', 'boxOfficeInfo_acceptedPaymentDetail', 'boxOfficeInfo_phoneNumberDetail', 'social_twitter', 'upcomingEvents_tmr', 'upcomingEvents_tmc', 'upcomingEvents_sportxr-uk_asmglobalmanchester']
['id',
 'name',
 'type',
 'test',
 'url',
 'locale',
 'externalLinks_spotify',
 'externalLinks_instagram',
 'upcomingEvents__total',
 'upcomingEvents__filtered',
 '_links_self',
 'upcomingEvents_universe',
 'upcomingEvents_ticketmaster',
 'externalLinks_youtube',
 'externalLinks_twitter',
 'externalLinks_itunes',
 'externalLinks_wiki',
 'externalLinks_facebook',
 'externalLinks_musicbrainz',
 'externalLinks_homepage',
 'externalLinks_lastfm',
 'upcomingEvents_mfx-fi',
 'upcomingEvents_mticket',
 'externalLinks_bandcamp',
 'externalLinks_tiktok',
 'externalLinks_soundcloud',
 'upcomingEvents_mfx-nl',
 'upcomingEvents_mfx-de',
 'upcomingEvents_mfx-cz',
 'upcomingEvents_mfx-dk',
 'upcomingEvents_mfx-be',
 'upcomingEvents_mfx-ch',
 'upcomingEvents_trium',
 'upcomingEvents_tmr',
 'upcomingEvents_wts-tr',
 'upcomingEvents_ticketweb',
 'upcomingEvents_moshtix',
 'draftStatus',
 'upcomingEvents_mfx-no',
 'upcomingEvents_mfx-se',
 'upcomingEvents_mfx-it',
 'upcomingEvents_mfx-at',
 'upcomingEvents_mfx-es',
 'upcomingEvents_mfx-pl',
 'upcomingEvents_mfx-ae',
 'upcomingEvents_crowder',
 'upcomingEvents_ticketnet',
 'upcomingEvents_tmc',
 'upcomingEvents_tixcraft-sg',
 'upcomingEvents_sportxr',
 'upcomingEvents_quicket',
 'upcomingEvents_mfx-za',
 'upcomingEvents_sportxtr']

Creating our genre - df.genre

In [124]:
# Start with core scalar event fields from the now-clean df
df_genre = df[['id', 'name', 'dates.start.localDate', 'dates.spanMultipleDays']].copy()

# Pull genre from df_classifications
df_genre = df_genre.merge(
    df_classifications[['id', 'genre_name', 'subGenre_name']],
    on='id', how='left'
)

# Pull venue city/region from df_venues
df_genre = df_genre.merge(
    df_venues[['id', 'city_name', 'state_name']],   # adjust names once confirmed
    on='id', how='left'
)

# Pull lineup genre summary from df_attractions
attraction_genre_summary = df_attractions.groupby('id').agg(
    attraction_count=('id', 'count'),
    attraction_genres=('genre_name', lambda x: list(x.dropna().unique()))  # adjust field name once confirmed
).reset_index().rename(columns={'id': 'event_id'})

df_genre = df_genre.merge(
    attraction_genre_summary, left_on='id', right_on='event_id', how='left'
)
df_genre = df_genre.drop(columns=['event_id'])

df_genre.head()

KeyError: "['state_name'] not in index"

In [119]:
df_attractions.head()

,id,name,type,test,url,locale,externalLinks_spotify,externalLinks_instagram,upcomingEvents__total,upcomingEvents__filtered,...,upcomingEvents_mfx-pl,upcomingEvents_mfx-ae,upcomingEvents_crowder,upcomingEvents_ticketnet,upcomingEvents_tmc,upcomingEvents_tixcraft-sg,upcomingEvents_sportxr,upcomingEvents_quicket,upcomingEvents_mfx-za,upcomingEvents_sportxtr
0,K8vZ917O7if,Dewin,attraction,False,https://www.ticketmaster.com/dewin-tickets/art...,en-us,[{'url': 'https://open.spotify.com/artist/1ers...,[{'url': 'https://www.instagram.com/dewinband/'}],0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,K8vZ917L9i0,Everywhere at Once,attraction,False,https://www.ticketmaster.com/everywhere-at-onc...,en-us,NaN,NaN,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,K8vZ917O7if,Dewin,attraction,False,https://www.ticketmaster.com/dewin-tickets/art...,en-us,[{'url': 'https://open.spotify.com/artist/1ers...,[{'url': 'https://www.instagram.com/dewinband/'}],0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,K8vZ917L9i0,Everywhere at Once,attraction,False,https://www.ticketmaster.com/everywhere-at-onc...,en-us,NaN,NaN,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,K8vZ917Khtf,Llangollen International Eisteddfod,attraction,False,https://www.ticketmaster.com/llangollen-intern...,en-us,NaN,NaN,6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [128]:
df_og['_embedded.attractions'].iloc[0]

[{'name': 'Dewin',
  'type': 'attraction',
  'id': 'K8vZ917O7if',
  'test': False,
  'url': 'https://www.ticketmaster.com/dewin-tickets/artist/4412873',
  'locale': 'en-us',
  'externalLinks': {'spotify': [{'url': 'https://open.spotify.com/artist/1ersOZ90l0IgAQMqSDnDvu'}],
   'instagram': [{'url': 'https://www.instagram.com/dewinband/'}]},
  'images': [{'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/c/f50/96fa13be-e395-429b-8558-a51bb9054f50_105951_TABLET_LANDSCAPE_LARGE_16_9.jpg',
    'width': 2048,
    'height': 1152,
    'fallback': True},
   {'ratio': '3_2',
    'url': 'https://s1.ticketm.net/dam/c/797/5e693c26-2881-4776-8f0c-3aa94bfa3797_106511_TABLET_LANDSCAPE_3_2.jpg',
    'width': 1024,
    'height': 683,
    'fallback': True},
   {'ratio': '3_2',
    'url': 'https://s1.ticketm.net/dam/c/797/5e693c26-2881-4776-8f0c-3aa94bfa3797_106511_ARTIST_PAGE_3_2.jpg',
    'width': 305,
    'height': 203,
    'fallback': True},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/c/797/5e693c26-2881-4776-8f0c-3aa94bfa3797_106511_EVENT_DETAIL_PAGE_16_9.jpg',
    'width': 205,
    'height': 115,
    'fallback': True},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/c/797/5e693c26-2881-4776-8f0c-3aa94bfa3797_106511_RETINA_LANDSCAPE_16_9.jpg',
    'width': 1136,
    'height': 639,
    'fallback': True},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/c/797/5e693c26-2881-4776-8f0c-3aa94bfa3797_106511_RETINA_PORTRAIT_16_9.jpg',
    'width': 640,
    'height': 360,
    'fallback': True},
   {'ratio': '4_3',
    'url': 'https://s1.ticketm.net/dam/c/797/5e693c26-2881-4776-8f0c-3aa94bfa3797_106511_CUSTOM.jpg',
    'width': 305,
    'height': 225,
    'fallback': True},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/c/797/5e693c26-2881-4776-8f0c-3aa94bfa3797_106511_RECOMENDATION_16_9.jpg',
    'width': 100,
    'height': 56,
    'fallback': True},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/c/797/5e693c26-2881-4776-8f0c-3aa94bfa3797_106511_TABLET_LANDSCAPE_16_9.jpg',
    'width': 1024,
    'height': 576,
    'fallback': True},
   {'ratio': '3_2',
    'url': 'https://s1.ticketm.net/dam/c/797/5e693c26-2881-4776-8f0c-3aa94bfa3797_106511_RETINA_PORTRAIT_3_2.jpg',
    'width': 640,
    'height': 427,
    'fallback': True}],
  'classifications': [{'primary': True,
    'segment': {'id': 'KZFzniwnSyZfZ7v7nJ', 'name': 'Music'},
    'genre': {'id': 'KnvZfZ7vAvv', 'name': 'Alternative'},
    'subGenre': {'id': 'KZazBEonSMnZfZ7vAvE',
     'name': 'Adult Alternative Pop/Rock'},
    'type': {'id': 'KZAyXgnZfZ7v7l1', 'name': 'Group'},
    'subType': {'id': 'KZFzBErXgnZfZ7vA71', 'name': 'Band'},
    'family': False}],
  'upcomingEvents': {'_total': 0, '_filtered': 0},
  '_links': {'self': {'href': '/discovery/v2/attractions/K8vZ917O7if?locale=en-us'}}},
 {'name': 'Everywhere at Once',
  'type': 'attraction',
  'id': 'K8vZ917L9i0',
  'test': False,
  'url': 'https://www.ticketmaster.com/everywhere-at-once-tickets/artist/4241369',
  'locale': 'en-us',
  'images': [{'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/a/ee7/50efe1c1-bfd7-405d-8d6b-3b8208abeee7_TABLET_LANDSCAPE_LARGE_16_9.jpg',
    'width': 2048,
    'height': 1152,
    'fallback': False},
   {'ratio': '4_3',
    'url': 'https://s1.ticketm.net/dam/a/ee7/50efe1c1-bfd7-405d-8d6b-3b8208abeee7_CUSTOM.jpg',
    'width': 305,
    'height': 225,
    'fallback': False},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/a/ee7/50efe1c1-bfd7-405d-8d6b-3b8208abeee7_RECOMENDATION_16_9.jpg',
    'width': 100,
    'height': 56,
    'fallback': False},
   {'ratio': '3_2',
    'url': 'https://s1.ticketm.net/dam/a/ee7/50efe1c1-bfd7-405d-8d6b-3b8208abeee7_RETINA_PORTRAIT_3_2.jpg',
    'width': 640,
    'height': 427,
    'fallback': False},
   {'ratio': '3_2',
    'url': 'https://s1.ticketm.net/dam/a/ee7/50efe1c1-bfd7-405d-8d6b-3b8208abeee7_ARTIST_PAGE_3_2.jpg',
    'width': 305,
    'height': 203,
    'fallback': False},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/a/ee7/50efe1c1-bfd7-405d-8d6b-3b8208abeee7_RETINA_PORTRAIT_16_9.jpg',
    'width': 640,
    'height': 360,
    'fallback': False},
   {'ratio': '3_2',
    'url': 'https://s1.ticketm.net/dam/a/ee7/50efe1c1-bfd7-405d-8d6b-3b8208abeee7_TABLET_LANDSCAPE_3_2.jpg',
    'width': 1024,
    'height': 683,
    'fallback': False},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/a/ee7/50efe1c1-bfd7-405d-8d6b-3b8208abeee7_EVENT_DETAIL_PAGE_16_9.jpg',
    'width': 205,
    'height': 115,
    'fallback': False},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/a/ee7/50efe1c1-bfd7-405d-8d6b-3b8208abeee7_TABLET_LANDSCAPE_16_9.jpg',
    'width': 1024,
    'height': 576,
    'fallback': False},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/a/ee7/50efe1c1-bfd7-405d-8d6b-3b8208abeee7_RETINA_LANDSCAPE_16_9.jpg',
    'width': 1136,
    'height': 639,
    'fallback': False},
   {'ratio': '1_1',
    'url': 'https://s1.ticketm.net/dam/a/ee7/50efe1c1-bfd7-405d-8d6b-3b8208abeee7_SOURCE',
    'width': 4688,
    'height': 4688,
    'fallback': False}],
  'classifications': [{'primary': True,
    'segment': {'id': 'KZFzniwnSyZfZ7v7nJ', 'name': 'Music'},
    'genre': {'id': 'KnvZfZ7vAvl', 'name': 'Other'},
    'subGenre': {'id': 'KZazBEonSMnZfZ7vk1I', 'name': 'Other'},
    'type': {'id': 'KZAyXgnZfZ7v7lt', 'name': 'Event Style'},
    'subType': {'id': 'KZFzBErXgnZfZ7vA6E', 'name': 'Festival'},
    'family': False}],
  'upcomingEvents': {'universe': 2, '_total': 2, '_filtered': 0},
  '_links': {'self': {'href': '/discovery/v2/attractions/K8vZ917L9i0?locale=en-us'}}}]

In [109]:
sample = df_og['_embedded.attractions'].dropna().iloc[0][0]

for key in ['classifications', 'aliases', '_links', 'images']:
    if key in sample:
        print(f"{key}: {type(sample[key]).__name__}")
    else:
        print(f"{key}: not present in this sample")

name: str
type: str
id: str
test: bool
url: str
locale: str
externalLinks: dict
images: list
classifications: list
upcomingEvents: dict
_links: dict

In [136]:
df_attractions.columns

Index(['id', 'name', 'type', 'test', 'url', 'locale', 'externalLinks_spotify',
       'externalLinks_instagram', 'upcomingEvents__total',
       'upcomingEvents__filtered', '_links_self', 'upcomingEvents_universe',
       'upcomingEvents_ticketmaster', 'externalLinks_youtube',
       'externalLinks_twitter', 'externalLinks_itunes', 'externalLinks_wiki',
       'externalLinks_facebook', 'externalLinks_musicbrainz',
       'externalLinks_homepage', 'externalLinks_lastfm',
       'upcomingEvents_mfx-fi', 'upcomingEvents_mticket',
       'externalLinks_bandcamp', 'externalLinks_tiktok',
       'externalLinks_soundcloud', 'upcomingEvents_mfx-nl',
       'upcomingEvents_mfx-de', 'upcomingEvents_mfx-cz',
       'upcomingEvents_mfx-dk', 'upcomingEvents_mfx-be',
       'upcomingEvents_mfx-ch', 'upcomingEvents_trium', 'upcomingEvents_tmr',
       'upcomingEvents_wts-tr', 'upcomingEvents_ticketweb',
       'upcomingEvents_moshtix', 'draftStatus', 'upcomingEvents_mfx-no',
       'upcomingEvents_mfx-se', 'upcomingEvents_mfx-it',
       'upcomingEvents_mfx-at', 'upcomingEvents_mfx-es',
       'upcomingEvents_mfx-pl', 'upcomingEvents_mfx-ae',
       'upcomingEvents_crowder', 'upcomingEvents_ticketnet',
       'upcomingEvents_tmc', 'upcomingEvents_tixcraft-sg',
       'upcomingEvents_sportxr', 'upcomingEvents_quicket',
       'upcomingEvents_mfx-za', 'upcomingEvents_sportxtr'],
      dtype='object')

The classification dict in the df_og['_embedded.attractions'] was completely removed by the build_nested_table function. So we need to unravel another layer from df_og['_embedded.attractions'] to get the classification info. Lets call this table attraction_genre

In [140]:
attraction_classification_rows = []
for _, event_row in df_og.iterrows():
    event_id = event_row['id']
    attractions_list = event_row.get('_embedded.attractions', [])
    
    if not isinstance(attractions_list, list):
        continue
    
    for attraction in attractions_list:
        attraction_id = attraction.get('id')
        classifications = attraction.get('classifications', [{}])
        c = classifications[0] if classifications else {}
        attraction_classification_rows.append({
            'event_id': event_id,
            'attraction_id': attraction_id,
            'attraction_genre': c.get('genre', {}).get('name'),
            'attraction_subGenre': c.get('subGenre', {}).get('name'),
        })

df_attraction_genres = pd.DataFrame(attraction_classification_rows)
df_attraction_genres.head()

,event_id,attraction_id,attraction_genre,attraction_subGenre
0,LvZ18QxAj1bZeL8vGSGnc,K8vZ917O7if,Alternative,Adult Alternative Pop/Rock
1,LvZ18QxAj1bZeL8vGSGnc,K8vZ917L9i0,Other,Other
2,LvZ18QxAj1bZeL8vGSGnc,K8vZ917O7if,Alternative,Adult Alternative Pop/Rock
3,LvZ18QxAj1bZeL8vGSGnc,K8vZ917L9i0,Other,Other
4,G5vHZ_dQ2CoCm,K8vZ917Khtf,Rock,Pop

Building our df_genre table

In [165]:
df_genre = df[['id', 'name', 'dates.start.localDate']].copy()

df_genre = df_genre.merge(
    df_classifications[['id', 'genre_name', 'subGenre_name']],
    on='id', how='left'
)

df_genre = df_genre.merge(
    df_venues[['event_id', 'city_name']],
    left_on='id', right_on='event_id', how='left'
)

attraction_genre_summary = df_attraction_genres.groupby('event_id').agg(
    attraction_count=('attraction_id', 'count'),
    attraction_genres=('attraction_genre', lambda x: list(x.dropna().unique()))
).reset_index().rename(columns={'event_id': 'id'})

df_genre = df_genre.merge(attraction_genre_summary, on='id', how='left')

df_genre.head()

,id,name,dates.start.localDate,genre_name,subGenre_name,event_id,city_name,attraction_count,attraction_genres
0,LvZ18QxAj1bZeL8vGSGnc,EVERYWHERE AT ONCE: Dewin,2026-06-28,Alternative,Adult Alternative Pop/Rock,LvZ18QxAj1bZeL8vGSGnc,"Narberth, Pembrokeshire",4.0,"[Alternative, Other]"
1,LvZ18QxAj1bZeL8vGSGnc,EVERYWHERE AT ONCE: Dewin,2026-06-28,Alternative,Adult Alternative Pop/Rock,LvZ18QxAj1bZeL8vGSGnc,"Narberth, Pembrokeshire",4.0,"[Alternative, Other]"
2,LvZ18QxAj1bZeL8vGSGnc,EVERYWHERE AT ONCE: Dewin,2026-06-28,Alternative,Adult Alternative Pop/Rock,LvZ18QxAj1bZeL8vGSGnc,"Narberth, Pembrokeshire",4.0,"[Alternative, Other]"
3,LvZ18QxAj1bZeL8vGSGnc,EVERYWHERE AT ONCE: Dewin,2026-06-28,Alternative,Adult Alternative Pop/Rock,LvZ18QxAj1bZeL8vGSGnc,"Narberth, Pembrokeshire",4.0,"[Alternative, Other]"
4,LvZ18QxAj1bZeL8vGSGnc,EVERYWHERE AT ONCE: Dewin,2026-06-28,Alternative,Adult Alternative Pop/Rock,LvZ18QxAj1bZeL8vGSGnc,"Narberth, Pembrokeshire",4.0,"[Alternative, Other]"

In [166]:
df_genre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2144 entries, 0 to 2143
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     2144 non-null   object
 1   name                   2144 non-null   object
 2   dates.start.localDate  2144 non-null   object
 3   genre_name             2144 non-null   object
 4   subGenre_name          2144 non-null   object
 5   event_id               2144 non-null   object
 6   city_name              2144 non-null   object
 7   attraction_count       2064 non-null   float64
 8   attraction_genres      2064 non-null   object
dtypes: float64(1), object(8)
memory usage: 150.9+ KB

In [167]:
null_vals(df_genre)

                       null  percent
attraction_count         80    3.731
attraction_genres        80    3.731
id                        0    0.000
name                      0    0.000
dates.start.localDate     0    0.000
genre_name                0    0.000
subGenre_name             0    0.000
event_id                  0    0.000
city_name                 0    0.000

In [169]:
df_genre.head

<bound method NDFrame.head of                          id  \
0     LvZ18QxAj1bZeL8vGSGnc
1     LvZ18QxAj1bZeL8vGSGnc
2     LvZ18QxAj1bZeL8vGSGnc
3     LvZ18QxAj1bZeL8vGSGnc
4     LvZ18QxAj1bZeL8vGSGnc
...                     ...
2139        1kuOv0o9GAuQxki
2140          G5dzZ_khSQFyh
2141          G5vHZ_5UMSbtO
2142          G5vHZ_5taClWc
2143          G5vHZ_kIknJnr

                                                   name dates.start.localDate  \
0                             EVERYWHERE AT ONCE: Dewin            2026-06-28
1                             EVERYWHERE AT ONCE: Dewin            2026-06-28
2                             EVERYWHERE AT ONCE: Dewin            2026-06-28
3                             EVERYWHERE AT ONCE: Dewin            2026-06-28
4                             EVERYWHERE AT ONCE: Dewin            2026-06-28
...                                                 ...                   ...
2139                                     The Black Keys            2026-08-31
2140  Earl Sweatshirt & MIKE - Home on the Range Tou...            2026-08-31
2141                                    Syd: Beard Tour            2026-08-31
2142                                       YHWH Nailgun            2026-08-31
2143                                         Lily Fitts            2026-08-31

       genre_name               subGenre_name               event_id  \
0     Alternative  Adult Alternative Pop/Rock  LvZ18QxAj1bZeL8vGSGnc
1     Alternative  Adult Alternative Pop/Rock  LvZ18QxAj1bZeL8vGSGnc
2     Alternative  Adult Alternative Pop/Rock  LvZ18QxAj1bZeL8vGSGnc
3     Alternative  Adult Alternative Pop/Rock  LvZ18QxAj1bZeL8vGSGnc
4     Alternative  Adult Alternative Pop/Rock  LvZ18QxAj1bZeL8vGSGnc
...           ...                         ...                    ...
2139         Rock            Alternative Rock        1kuOv0o9GAuQxki
2140  Hip-Hop/Rap                        Trap          G5dzZ_khSQFyh
2141  Hip-Hop/Rap                        Trap          G5vHZ_5UMSbtO
2142         Rock            Alternative Rock          G5vHZ_5taClWc
2143          Pop                 Electro Pop          G5vHZ_kIknJnr

                    city_name  attraction_count     attraction_genres
0     Narberth, Pembrokeshire               4.0  [Alternative, Other]
1     Narberth, Pembrokeshire               4.0  [Alternative, Other]
2     Narberth, Pembrokeshire               4.0  [Alternative, Other]
3     Narberth, Pembrokeshire               4.0  [Alternative, Other]
4     Narberth, Pembrokeshire               4.0  [Alternative, Other]
...                       ...               ...                   ...
2139                   London               1.0                [Rock]
2140                   London               2.0         [Hip-Hop/Rap]
2141               Manchester               1.0         [Hip-Hop/Rap]
2142               Nottingham               1.0         [Alternative]
2143                  Bristol               1.0                 [Pop]

[2144 rows x 9 columns]>

In [170]:
df_genre.to_csv("df_genre.csv", index=False)

In [183]:
df_og['dates.spanMultipleDays'].unique()

array([False])

In [177]:
df_og.columns.tolist()

['name',
 'type',
 'id',
 'test',
 'description',
 'url',
 'locale',
 'images',
 'classifications',
 'nameOrigin',
 'sales.public.startDateTime',
 'sales.public.startTBD',
 'sales.public.startTBA',
 'sales.public.endDateTime',
 'dates.access.startDateTime',
 'dates.access.startApproximate',
 'dates.access.endDateTime',
 'dates.access.endApproximate',
 'dates.start.localDate',
 'dates.start.localTime',
 'dates.start.dateTime',
 'dates.start.dateTBD',
 'dates.start.dateTBA',
 'dates.start.timeTBA',
 'dates.start.noSpecificTime',
 'dates.end.localTime',
 'dates.end.dateTime',
 'dates.end.approximate',
 'dates.end.noSpecificTime',
 'dates.timezone',
 'dates.status.code',
 'dates.spanMultipleDays',
 '_links.self.href',
 '_links.attractions',
 '_links.venues',
 '_embedded.venues',
 '_embedded.attractions',
 'promoters',
 'pleaseNote',
 'promoter.id',
 'promoter.name',
 'promoter.description',
 'accessibility.ticketLimit',
 'ageRestrictions.legalAgeEnforced',
 'ticketing.safeTix.enabled',
 'ticketing.allInclusivePricing.enabled',
 'ticketTextLines.en-gb.line6',
 'ticketTextLines.en-gb.line5',
 'ticketTextLines.en-gb.line4',
 'ticketTextLines.en-gb.line3',
 'ticketTextLines.en-gb.line2',
 'ticketTextLines.en-gb.line1',
 'ticketLimit.info',
 'info',
 'sales.presales',
 'seatmap.staticUrl',
 'linkMoreInfo.descriptions.ca-es',
 'linkMoreInfo.descriptions.de-de',
 'linkMoreInfo.descriptions.en-es',
 'linkMoreInfo.descriptions.en-us',
 'linkMoreInfo.descriptions.en-de',
 'linkMoreInfo.descriptions.es-es',
 'linkMoreInfo.descriptions.en-gb',
 'linkMoreInfo.url',
 'accessibility.info',
 'accessibility.url',
 'accessibility.urlText',
 'products',
 'attractionGroups.attractionId',
 'attractionGroups.major.id',
 'attractionGroups.major.name',
 'dates.end.localDate',
 'ageRestrictions.ageRuleDescription',
 'attractionGroups.major.description',
 'attractionGroups.major.descriptions.tm-df',
 'attractionGroups.major.descriptions.en-gb',
 'attractionGroups.minor.id',
 'attractionGroups.minor.name',
 'dates.initialStartDate.localDate',
 'dates.initialStartDate.localTime',
 'dates.initialStartDate.dateTime']